#!/usr/bin/env python3
"""Builds the AuroraOS CPU stress app (CPUStress.bin, beside this file).

1. The ARM11 job: arm11/job.c and ../common/work.c, compiled for the ARM11
   with the flags the Horizon build uses (../horizon/Makefile), linked at
   JOB11_CODE and turned into build/job11_blob.h.
2. The app, with the SDK (../../sdk/aurcc.py): main.c, the shared test, and
   the blob, which main.c copies into place at start.

Run from anywhere: py cpu-stress/aurora/build.py [-v]
"""
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
COMMON = HERE.parent / "common"
REPO = HERE.parent.parent
BUILD = HERE / "build"
CC = "arm-none-eabi-gcc"
OBJCOPY = "arm-none-eabi-objcopy"

# As ../horizon/Makefile compiles work.c, plus what running outside Horizon
# needs: no C library, and SCTLR.U is clear on AuroraOS's ARM11.
ARM11 = ["-march=armv6k", "-mtune=mpcore", "-mfloat-abi=hard", "-marm"]
FLAGS = ["-O2", "-mword-relocations", "-ffunction-sections",
         "-fno-tree-loop-distribute-patterns"]
CFLAGS = ARM11 + FLAGS + ["-g", "-Wall", "-Wextra", "-ffreestanding",
                          "-fno-builtin", "-mno-unaligned-access",
                          "-I", str(COMMON), "-I", str(HERE / "arm11")]

verbose = "-v" in sys.argv[1:]


def run(cmd):
    if verbose:
        print("  $ " + " ".join(str(c) for c in cmd))
    r = subprocess.run([str(c) for c in cmd])
    if r.returncode:
        sys.exit(r.returncode)


def blob_header(data: bytes, build: str) -> str:
    lines = ["/* Generated by build.py from arm11/ and ../common/work.c. */",
             f'#define JOB11_BUILD "{build}"',
             f"#define JOB11_SIZE {len(data)}u",
             "static const unsigned char job11_blob[] = {"]
    for i in range(0, len(data), 16):
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    if not shutil.which(CC):
        sys.exit(f"{CC} was not found on PATH (devkitARM)")
    BUILD.mkdir(exist_ok=True)
    objs = []
    for src in (HERE / "arm11" / "job.c", COMMON / "work.c"):
        obj = BUILD / (src.stem + "11.o")
        run([CC, *CFLAGS, "-c", src, "-o", obj])
        objs.append(obj)
    elf = BUILD / "job11.elf"
    run([CC, *ARM11, "-T", HERE / "arm11" / "job11.ld", "-nostdlib",
         "-nostartfiles", "-Wl,--build-id=none", "-Wl,--gc-sections",
         *objs, "-o", elf])
    bin_path = BUILD / "job11.bin"
    run([OBJCOPY, "-O", "binary", elf, bin_path])
    data = bin_path.read_bytes()
    if len(data) > 0x80000:
        sys.exit("the ARM11 job is larger than JOB11_CODE_MAX")
    version = subprocess.run([CC, "-dumpversion"], capture_output=True,
                             text=True).stdout.strip()
    build = f"gcc {version}, " + " ".join(ARM11[:3] + FLAGS[:1]) + \
        " (an ARM11 job, built as the Horizon version builds)"
    (BUILD / "job11_blob.h").write_text(blob_header(data, build),
                                        encoding="ascii", newline="\n")
    print(f"ARM11 job: {len(data)} bytes")

    run([sys.executable, REPO / "sdk" / "aurcc.py", "build",
         HERE / "main.c", COMMON / "stress.c", COMMON / "draw.c",
         COMMON / "work.c",
         "-I", COMMON, "-I", HERE / "arm11", "-I", BUILD,
         "--icon", HERE / "CPUStress.icon",
         "-o", HERE / "CPUStress.bin", *(["-v"] if verbose else [])])


if __name__ == "__main__":
    main()
