#ifndef AURORA_LANG_H
#define AURORA_LANG_H

#include "user.h"

typedef enum {
  /* Progress-bar labels: must stay first and in step order (0..4). */
  STR_LANGUAGE = 0,
  STR_NETWORK,
  STR_DETAILS,
  STR_PERSONAL,
  STR_WELCOME,

  STR_GET_STARTED,

  STR_NET_L1,
  STR_NET_L2,
  STR_WIFI_UNAVAIL,
  STR_SKIP,
  STR_NET_HINT,

  STR_USER_L1,
  STR_USER_L2,
  STR_USER_NAME,
  STR_DAY,
  STR_MONTH,
  STR_YEAR,
  STR_BACK,
  STR_NEXT,
  STR_USER_HINT,

  STR_KB_ENTER_NAME,

  STR_PERS_L1,
  STR_PERS_HINT,

  STR_PRESS_A_START,
  STR_B_BACK,

  STR_SETTINGS,
  STR_WIFI,
  STR_ACCENT_COLOR,
  STR_BRIGHTNESS,
  STR_ABOUT,
  STR_OFF,
  STR_PICK_ACCENT,
  STR_A_APPLY_B_BACK,
  STR_POWER_OFF,
  STR_SYSTEM,
  STR_EMPTY_SLOT,
  STR_LOADING,
  STR_MUSIC,
  STR_NO_TRACKS,
  STR_PLAYING,
  STR_STOPPED,
  STR_DEBUG_CRASH,
  STR_WIFI_TEST,
  STR_GPU_TEST,

  STR_VERSION,
  STR_CONSOLE,
  STR_BATTERY,
  STR_SD_CARD,
  STR_LICENSE,
  STR_CHARGING,
  STR_FREE,
  STR_NO_CARD,

  STR_CORE_OLD,
  STR_CORE_OLD_HINT,
  STR_LATER,

  STR_TOUCH_CAL,
  STR_CAL_TAP,
  STR_CAL_HINT,
  STR_CAL_POINT,
  STR_CAL_CHECK,
  STR_CAL_CHECK_HINT,
  STR_CAL_RETRY,
  STR_CAL_SAVED,
  STR_CAL_SAVE_FAILED,
  STR_CUSTOM,
  STR_DEFAULT,

  STR_MORE_INFO,
  STR_SOFTWARE_UPDATE,
  STR_UPDATE_NONE,
  STR_EMMC_CID,
  STR_DEVICE,
  STR_NOT_AVAILABLE,

  STR_CLOCK,
  STR_CLOCK_HINT,
  STR_CLOCK_KEYS,
  STR_HOUR,
  STR_MINUTE,

  STR_FOLDER,
  STR_HOME,
  STR_ITEM,
  STR_ITEMS,
  STR_MOVE,
  STR_MOVE_TO,
  STR_NEW_FOLDER,
  STR_RENAME,
  STR_REMOVE_FOLDER,
  STR_CANCEL,
  STR_POWER_ASK,
  STR_REMOVE_ASK,
  STR_REMOVE_HINT,
  STR_FOLDER_NAME,
  STR_MOVE_KEYS,
  STR_MOVE_TOUCH,
  STR_CANT_MOVE,
  STR_ERR_FULL,
  STR_ERR_DEEP,
  STR_ERR_FOLDERS,
  STR_ERR_INSIDE,

  STR_COUNT
} StringId;

/* LANG_* */
extern int g_lang;

const char *L(StringId id);

#endif
