"""Auric code generator: type-checked AST -> freestanding C.

The C is compiled by arm-none-eabi-gcc with AuroraOS's exact ARM9 flags and
linked against the runtime shim (../runtime). Transpiling to C rather than
emitting ARM directly is a deliberate choice, per the project plan.

Conventions in the generated C:
  * every user function/variable is prefixed `au_` so it can never collide with
    a C keyword or a runtime symbol; `fn main` becomes `au_main`, which the
    crt0 (auric_start.s) branches to.
  * built-in calls lower to the shim's `aur_*` helpers.
  * predefined constants (colours, buttons) lower to macros in auric_runtime.h.
  * binary/unary expressions are fully parenthesized so C precedence can never
    change the meaning the type checker validated.
"""
from __future__ import annotations

from . import ast
from .prelude import BUILTINS, CONSTANTS

C_TYPE = {
    "int": "int",
    "float": "float",
    "bool": "int",
    "string": "const char *",
    "void": "void",
}

HEADER = (
    "/* Generated by aurc -- the Auric compiler. DO NOT EDIT.\n"
    " * Transpiled from Auric source; built freestanding for AuroraOS (ARM9).\n"
    " */\n"
    '#include "auric_runtime.h"\n'
)


class CodeGen:
    def __init__(self, program: ast.Program) -> None:
        self.program = program
        self.lines: list[str] = []

    @staticmethod
    def _mangle(name: str) -> str:
        return "au_" + name

    @staticmethod
    def _c_string(s: str) -> str:
        out = ['"']
        for ch in s:
            if ch == "\\":
                out.append("\\\\")
            elif ch == '"':
                out.append('\\"')
            elif ch == "\n":
                out.append("\\n")
            elif ch == "\t":
                out.append("\\t")
            elif ch == "\r":
                out.append("\\r")
            elif ch == "\0":
                out.append("\\0")
            elif 0x20 <= ord(ch) < 0x7F:
                out.append(ch)
            else:
                out.append(f"\\x{ord(ch) & 0xFF:02x}")
        out.append('"')
        return "".join(out)

    def _emit(self, line: str, indent: int) -> None:
        self.lines.append("  " * indent + line if line else "")

    def generate(self) -> str:
        self.lines = [HEADER]

        # Forward declarations: Auric allows calling a function before it is
        # textually defined.
        self.lines.append("/* forward declarations */")
        for fn in self.program.functions:
            self.lines.append(self._signature(fn) + ";")
        self.lines.append("")

        for fn in self.program.functions:
            self._gen_fn(fn)
        return "\n".join(self.lines) + "\n"

    def _signature(self, fn: ast.FnDecl) -> str:
        params = ", ".join(f"{C_TYPE[p.type]} {self._mangle(p.name)}"
                           for p in fn.params)
        return f"{C_TYPE[fn.ret_type]} {self._mangle(fn.name)}({params or 'void'})"

    def _gen_fn(self, fn: ast.FnDecl) -> None:
        self._emit(self._signature(fn) + " {", 0)
        self._gen_block_body(fn.body, 1)
        self._emit("}", 0)
        self._emit("", 0)

    def _gen_block_body(self, block: ast.Block, indent: int) -> None:
        for stmt in block.statements:
            self._gen_stmt(stmt, indent)

    def _gen_stmt(self, stmt: ast.Stmt, indent: int) -> None:
        if isinstance(stmt, ast.LetStmt):
            ctype = C_TYPE[stmt.decl_type or stmt.value.type]
            self._emit(f"{ctype} {self._mangle(stmt.name)} = "
                       f"{self._gen_expr(stmt.value)};", indent)

        elif isinstance(stmt, ast.AssignStmt):
            self._emit(f"{self._mangle(stmt.name)} = "
                       f"{self._gen_expr(stmt.value)};", indent)

        elif isinstance(stmt, ast.IfStmt):
            self._emit(f"if ({self._gen_expr(stmt.cond)}) {{", indent)
            self._gen_block_body(stmt.then_block, indent + 1)
            if isinstance(stmt.else_block, ast.IfStmt):
                self._emit("} else {", indent)
                self._gen_stmt(stmt.else_block, indent + 1)
                self._emit("}", indent)
            elif isinstance(stmt.else_block, ast.Block):
                self._emit("} else {", indent)
                self._gen_block_body(stmt.else_block, indent + 1)
                self._emit("}", indent)
            else:
                self._emit("}", indent)

        elif isinstance(stmt, ast.WhileStmt):
            self._emit(f"while ({self._gen_expr(stmt.cond)}) {{", indent)
            self._gen_block_body(stmt.body, indent + 1)
            self._emit("}", indent)

        elif isinstance(stmt, ast.ReturnStmt):
            if stmt.value is None:
                self._emit("return;", indent)
            else:
                self._emit(f"return {self._gen_expr(stmt.value)};", indent)

        elif isinstance(stmt, ast.ExprStmt):
            self._emit(f"{self._gen_expr(stmt.expr)};", indent)

        elif isinstance(stmt, ast.Block):
            self._emit("{", indent)
            self._gen_block_body(stmt, indent + 1)
            self._emit("}", indent)

    def _gen_expr(self, expr: ast.Expr) -> str:
        if isinstance(expr, ast.IntLit):
            return str(expr.value)
        if isinstance(expr, ast.FloatLit):
            return repr(expr.value) + "f"
        if isinstance(expr, ast.BoolLit):
            return "1" if expr.value else "0"
        if isinstance(expr, ast.StringLit):
            return self._c_string(expr.value)
        if isinstance(expr, ast.VarExpr):
            # The type checker forbids locals/params from reusing a prelude
            # name, so a name in CONSTANTS is unambiguously the constant and
            # everything else is a mangled local/param.
            const = CONSTANTS.get(expr.name)
            if const is not None:
                return const.c_expr
            return self._mangle(expr.name)
        if isinstance(expr, ast.UnaryExpr):
            return f"({expr.op}{self._gen_expr(expr.operand)})"
        if isinstance(expr, ast.BinaryExpr):
            return (f"({self._gen_expr(expr.left)} {expr.op} "
                    f"{self._gen_expr(expr.right)})")
        if isinstance(expr, ast.CallExpr):
            builtin = BUILTINS.get(expr.callee)
            cname = builtin.c_name if builtin else self._mangle(expr.callee)
            args = ", ".join(self._gen_expr(a) for a in expr.args)
            return f"{cname}({args})"
        raise AssertionError(f"unhandled expr {type(expr).__name__}")
