"""Auric app icons.

Each compiled app embeds a 32x32, 1-bit icon at a fixed offset in its payload,
which the AuroraOS Home Menu reads and draws. This module parses a simple text
icon into the 128-byte packed form AuroraOS expects (ICON_SIZE=32,
ICON_ROW_BYTES=4, most-significant-bit first within each row byte -- matching
draw_icon_32 in ../../src/screen.c) and emits the little assembly header that
places the branch-to-entry + "AURICON1" magic + icon at the payload start.

Text icon format: up to 32 lines of up to 32 columns. A pixel is "on" if its
character is one of `# * X O @ 8`, otherwise "off". Lines beginning with `;`
(after optional spaces) are comments. Missing rows/columns are treated as off.
"""
from __future__ import annotations

from pathlib import Path

from .errors import AuricError

ICON_SIZE = 32
ICON_ROW_BYTES = 4
ICON_BYTES = ICON_SIZE * ICON_ROW_BYTES  # 128
MAGIC = "AURICON1"

_ON = set("#*XO@8")


def parse_icon_text(text: str) -> bytes:
    """Parse a text icon into 128 packed bytes."""
    rows = [ln.rstrip("\r\n") for ln in text.split("\n")
            if not ln.lstrip().startswith(";")]
    out = bytearray(ICON_BYTES)
    for r in range(ICON_SIZE):
        row = rows[r] if r < len(rows) else ""
        for c in range(ICON_SIZE):
            ch = row[c] if c < len(row) else " "
            if ch in _ON:
                out[r * ICON_ROW_BYTES + (c // 8)] |= 0x80 >> (c % 8)
    return bytes(out)


def load_icon(path: Path) -> bytes:
    try:
        return parse_icon_text(path.read_text(encoding="utf-8"))
    except OSError as e:
        raise AuricError(f"cannot read icon file {path}: {e}", stage="icon")


def default_icon() -> bytes:
    """A generic framed-tile icon for apps that don't supply their own."""
    out = bytearray(ICON_BYTES)

    def setpx(x: int, y: int) -> None:
        out[y * ICON_ROW_BYTES + (x // 8)] |= 0x80 >> (x % 8)

    for y in range(ICON_SIZE):
        for x in range(ICON_SIZE):
            border = x < 3 or x >= ICON_SIZE - 3 or y < 3 or y >= ICON_SIZE - 3
            center = 11 <= x < 21 and 11 <= y < 21
            if border or center:
                setpx(x, y)
    return bytes(out)


def emit_header_asm(icon: bytes) -> str:
    """Emit the .aurhead assembly embedding `icon` at the payload start."""
    if len(icon) != ICON_BYTES:
        raise AuricError(f"icon must be {ICON_BYTES} bytes, got {len(icon)}",
                         stage="icon")
    lines = [
        "/* Generated by aurc: Auric app header + icon block. DO NOT EDIT. */",
        '.section .aurhead, "ax"',
        ".arm",
        ".global _aur_header",
        "_aur_header:",
        "    b _start",              # offset 0: skip the icon block into crt0
        f'    .ascii "{MAGIC}"',     # offset 4: 8-byte magic
    ]
    for i in range(0, ICON_BYTES, 12):  # offset 12: 128 icon bytes
        chunk = icon[i:i + 12]
        lines.append("    .byte " + ", ".join(f"0x{b:02x}" for b in chunk))
    return "\n".join(lines) + "\n"
